name: Cleanup expired slides
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Call cleanup API
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
        run: |
          curl -fsS "$VERCEL_URL/api/cron/cleanup-expired-slides?secret=$CRON_SECRET"
